logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    fr.codecake.chatgptchallenge: INFO

management:
  prometheus:
    metrics:
      export:
        enabled: false

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${POSTGRESQL_ADDON_USER}
    password: ${POSTGRESQL_ADDON_PASSWORD}
    hikari:
      maximumPoolSize: 2
      schema: ${SCHEMA_DB}
  jpa:
    liquibase:
      contexts: prod
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${SSO_PROVIDER_OIDC_ISSUER_URI}
        registration:
          oidc:
            client-id: ${SSO_CLIENT_ID}
            client-secret: ${SSO_CLIENT_SECRET}
